name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-production:
    name: Deploy to Server
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -H clement.laatar.takima.cloud >> ~/.ssh/known_hosts

      - name: Deploy with Ansible
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          cd Ansible/my-project/ansible
          ansible-playbook -i inventories/setup.yml playbook.yml \
            -e "postgres_db=$POSTGRES_DB" \
            -e "postgres_user=$POSTGRES_USER" \
            -e "postgres_password=$POSTGRES_PASSWORD" \
            -e "dockerhub_username=$DOCKERHUB_USERNAME" \
            -e "backend_network=backend-network" \
            -e "frontend_network=frontend-network"
