name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-production:
    # Only run if the build workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H clement.laatar.takima.cloud >> ~/.ssh/known_hosts

      - name: Create Ansible vault file
        run: |
          mkdir -p Ansible/my-project/ansible/group_vars
          cat > Ansible/my-project/ansible/group_vars/all.yml << EOF
          postgres_db: ${{ secrets.POSTGRES_DB }}
          postgres_user: ${{ secrets.POSTGRES_USER }}
          postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          backend_network: backend-network
          frontend_network: frontend-network
          EOF

      - name: Deploy with Ansible
        run: |
          cd Ansible/my-project/ansible
          ansible-playbook -i inventories/setup.yml playbook.yml
